/*
Package gosros is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /home/karim/github.com/openconfig/ygot/genutil/names.go
using the following YANG input files:
	- yang/ietf-inet-types.yang
	- yang/ietf-yang-types.yang
	- yang/nokia-conf-combined.yang
	- yang/nokia-features.yang
	- yang/nokia-sros-yang-extensions.yang
	- yang/nokia-types-application-assurance.yang
	- yang/nokia-types-bfd.yang
	- yang/nokia-types-bgp.yang
	- yang/nokia-types-card.yang
	- yang/nokia-types-cellular.yang
	- yang/nokia-types-cflowd.yang
	- yang/nokia-types-chassis.yang
	- yang/nokia-types-dhcp.yang
	- yang/nokia-types-diameter.yang
	- yang/nokia-types-esa.yang
	- yang/nokia-types-eth-cfm.yang
	- yang/nokia-types-filter.yang
	- yang/nokia-types-igmp.yang
	- yang/nokia-types-igp.yang
	- yang/nokia-types-ipsec.yang
	- yang/nokia-types-isa.yang
	- yang/nokia-types-isis.yang
	- yang/nokia-types-l2tp.yang
	- yang/nokia-types-ldp.yang
	- yang/nokia-types-lldp.yang
	- yang/nokia-types-log.yang
	- yang/nokia-types-mcast-cac.yang
	- yang/nokia-types-mcast-mgmt.yang
	- yang/nokia-types-mcr.yang
	- yang/nokia-types-mpls.yang
	- yang/nokia-types-nat.yang
	- yang/nokia-types-oam.yang
	- yang/nokia-types-ospf.yang
	- yang/nokia-types-pcc-rule.yang
	- yang/nokia-types-pim.yang
	- yang/nokia-types-policy.yang
	- yang/nokia-types-port.yang
	- yang/nokia-types-ppp.yang
	- yang/nokia-types-ptp.yang
	- yang/nokia-types-qos.yang
	- yang/nokia-types-radius.yang
	- yang/nokia-types-redundancy.yang
	- yang/nokia-types-ripng.yang
	- yang/nokia-types-rip.yang
	- yang/nokia-types-router.yang
	- yang/nokia-types-rsvp.yang
	- yang/nokia-types-security.yang
	- yang/nokia-types-services.yang
	- yang/nokia-types-sfm.yang
	- yang/nokia-types-sros.yang
	- yang/nokia-types-subscriber-mgmt.yang
	- yang/nokia-types-system.yang
	- yang/nokia-types-vrrp.yang
	- yang/nokia-types-wlangw.yang
	- yang/nokia-types-wlan.yang
Imported modules were sourced from:
*/
package gosros

// Device represents the /device YANG schema element.
type Device struct {
	Configure *NokiaConf_Configure `path:"configure" module:"nokia-conf"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}
